/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const Project2LazyImport = createFileRoute('/project2')()
const Project1LazyImport = createFileRoute('/project1')()

// Create/Update Routes

const Project2LazyRoute = Project2LazyImport.update({
  path: '/project2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/project2.lazy').then((d) => d.Route))

const Project1LazyRoute = Project1LazyImport.update({
  path: '/project1',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/project1.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/project1': {
      preLoaderRoute: typeof Project1LazyImport
      parentRoute: typeof rootRoute
    }
    '/project2': {
      preLoaderRoute: typeof Project2LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  Project1LazyRoute,
  Project2LazyRoute,
])

/* prettier-ignore-end */
